source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.2'
gem 'active_storage_validations'
gem 'bcrypt'
# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.4', require: false
gem 'clearance'
# Use Active Model has_secure_password
gem 'cancancan'
gem 'dotenv-rails'
gem 'global'
gem 'grape'
gem 'grape-entity'
gem 'grape-kaminari'
# Command - rails grape:routes
gem 'grape_on_rails_routes'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# Use Active Storage variant
gem 'i18n-tasks', '~> 0.9.34'
gem 'image_processing', '~> 1.2'
gem 'interactor'
gem 'jbuilder', '~> 2.7'
gem 'jsonapi-serializer'
gem 'kaminari'
# Use postgresql as the database for Active Record
gem 'pg', '~> 1.1'
gem 'phony_rails'
gem 'postmark-rails'
gem 'prawn'
gem 'prawn-table'
# Use Puma as the app server
gem 'puma', '~> 5.0'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 6.1.4', '>= 6.1.4.1'
gem 'ransack'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Rubocop rails is used for code formatting. Rubocop gem is not needed if rubocop-rails gem is used.
gem 'rubocop-rails', require: false
gem 'sidekiq'
gem 'simple_form'

# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i(mingw mswin x64_mingw jruby)
# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
gem 'webpacker', '~> 5.0'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'bullet'
  gem 'byebug', platforms: %i(mri mingw x64_mingw)
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'pdf-inspector', require: "pdf/inspector"
  gem 'pry-rails'
  gem 'rspec-rails'
  gem 'shoulda-matchers'
end

group :development do
  # Display performance information such as SQL time and flame graphs for each request in your browser.
  # Can be configured to work on production as well see: https://github.com/MiniProfiler/rack-mini-profiler/blob/master/README.md
  gem 'letter_opener'
  gem 'listen', '~> 3.3'
  gem 'rack-mini-profiler', '~> 2.0'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 4.1.0'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 3.26'
  gem 'database_cleaner'
  gem 'rails-controller-testing'
  gem 'selenium-webdriver'
  # Easy installation and use of web drivers to run system tests with browsers
  gem 'webdrivers'
end
